<?php

namespace ContainerLQ6sELB;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZzG1bddService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zzG1bdd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zzG1bdd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\PageController::checkLogin' => ['privates', '.service_locator.uSVyOez', 'get_ServiceLocator_USVyOezService', true],
            'App\\Controller\\PageController::checkfavorite' => ['privates', '.service_locator.uSVyOez', 'get_ServiceLocator_USVyOezService', true],
            'App\\Controller\\PageController::checkregister' => ['privates', '.service_locator.uSVyOez', 'get_ServiceLocator_USVyOezService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PageController:checkLogin' => ['privates', '.service_locator.uSVyOez', 'get_ServiceLocator_USVyOezService', true],
            'App\\Controller\\PageController:checkfavorite' => ['privates', '.service_locator.uSVyOez', 'get_ServiceLocator_USVyOezService', true],
            'App\\Controller\\PageController:checkregister' => ['privates', '.service_locator.uSVyOez', 'get_ServiceLocator_USVyOezService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PageController::checkLogin' => '?',
            'App\\Controller\\PageController::checkfavorite' => '?',
            'App\\Controller\\PageController::checkregister' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PageController:checkLogin' => '?',
            'App\\Controller\\PageController:checkfavorite' => '?',
            'App\\Controller\\PageController:checkregister' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
