<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2BCE8XI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2BCE8XI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2BCE8XI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2BCE8XI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2BCE8XI\App_KernelDevDebugContainer([
    'container.build_hash' => '2BCE8XI',
    'container.build_id' => 'e1804e84',
    'container.build_time' => 1692328249,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2BCE8XI');
