<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_page_index' => [[], ['_controller' => 'App\\Controller\\PageController::index'], [], [['text', '/']], [], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\PageController::login'], [], [['text', '/login']], [], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\PageController::register'], [], [['text', '/register']], [], [], []],
    'homepage' => [[], ['_controller' => 'App\\Controller\\PageController::home'], [], [['text', '/homepage']], [], [], []],
    'app_page_userinfo' => [[], ['_controller' => 'App\\Controller\\PageController::userinfo'], [], [['text', '/userSettings']], [], [], []],
    'app_page_userbookmark' => [['movieId'], ['_controller' => 'App\\Controller\\PageController::userbookmark'], [], [['variable', '/', '[^/]++', 'movieId', true], ['text', '/favorites']], [], [], []],
    'app_page_movieinfo' => [['movieId'], ['_controller' => 'App\\Controller\\PageController::movieInfo'], [], [['variable', '/', '[^/]++', 'movieId', true], ['text', '/movie']], [], [], []],
    'app_page_checklogin' => [[], ['_controller' => 'App\\Controller\\PageController::checkLogin'], [], [['text', '/checkLogin']], [], [], []],
    'app_page_checkregister' => [[], ['_controller' => 'App\\Controller\\PageController::checkregister'], [], [['text', '/checkregister']], [], [], []],
    'app_page_checkfavorite' => [[], ['_controller' => 'App\\Controller\\PageController::checkfavorite'], [], [['text', '/checkfavorite']], [], [], []],
];
